{% set name = "hexalattice" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb5fd70efb6afe44c1e0919ee5f1912554999620bca56d2aa0b04a1b229b7e87

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    # the package lists numpy and matplotlib as setup requirements even though
    # they are not needed
    - numpy
    - matplotlib-base
  run:
    - python >=3.6
    - numpy
    - matplotlib-base

test:
  imports:
    - hexalattice

about:
  home: https://github.com/alexkaz2/hexalattice
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create and plot hexagonal lattices

extra:
  recipe-maintainers:
    - beckermr
