{% set name = "hexalattice" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58acdc6da8aa13553d7155ca36b54f7572aba0f6e63436ed0391e5a9e5f28ce4

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    # the package lists numpy and matplotlib as setup requirements even though
    # they are not needed
    - numpy
    - matplotlib-base
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - hexalattice

about:
  home: https://github.com/alexkaz2/hexalattice
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create and plot hexagonal lattices

extra:
  recipe-maintainers:
    - beckermr
